version: "3"

services:
  node-front:
    build:
      context: .
      dockerfile: Dockerfile.node
#    user: node
    working_dir: /home/node
    tty: true
    stdin_open: true
    command: node

    ports:
      - 3001:3000
      - 9001:9000
      - 8080:8080
      - 5173:5173
    volumes:
      - .:/home/node
