version: "3"

services:
  node-front:
    build:
      context: .
      dockerfile: Dockerfile.node
    working_dir: /home/node
    tty: true
    stdin_open: true
    command: node

    ports:
      - 8080:8080
    volumes:
      - .:/home/node
